spring.application.name=api-gateway

# Puerto del Gateway
server.port=8080

# Configuracion de EUREKA
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Ruta para el microservicio de USUARIOS
spring.cloud.gateway.server.webflux.routes[0].id=usuarios-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://usuarios-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/usuarios/**

# Ruta para el microservicio de AUTHS
spring.cloud.gateway.server.webflux.routes[1].id=auth-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/registros/**

# Ruta para el microservicio de ALBUMES
spring.cloud.gateway.server.webflux.routes[2].id=albumes-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://albumes-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/albumes/**

# Ruta para el microservicio de CANCIONES
spring.cloud.gateway.server.webflux.routes[3].id=canciones-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://canciones-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/canciones/**

# Ruta para el microservicio de PLAYLISTS
spring.cloud.gateway.server.webflux.routes[4].id=playlists-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://playlists-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/playlists-canciones/**

# Ruta para el microservicio de REPORTES
spring.cloud.gateway.server.webflux.routes[5].id=reportes-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://reportes-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/v1/reportes/**

# Ruta para el microservicio de REPRODUCCIONES
spring.cloud.gateway.server.webflux.routes[6].id=reproducciones-service
spring.cloud.gateway.server.webflux.routes[6].uri=lb://reproducciones-service
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/v1/reproducciones/**

# Ruta para el microservicio de SUSCRIPCIONES
spring.cloud.gateway.server.webflux.routes[7].id=suscripciones-service
spring.cloud.gateway.server.webflux.routes[7].uri=lb://suscripciones-service
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/v1/suscripciones/**